#ifndef TRAVELPI_APP_CONFIG_H
#define TRAVELPI_APP_CONFIG_H

#define TRAVELPI_TARGET_FPS 60
#define TRAVELPI_DEFAULT_SCREEN_WIDTH 1920
#define TRAVELPI_DEFAULT_SCREEN_HEIGHT 1080

#define TRAVELPI_TRIPS_CONFIG_PATH "config/trips.json"
#define TRAVELPI_BANNER_FONT_PATH "assets/fonts/LibreBaskerville.ttf"
#define TRAVELPI_BANNER_FONT_BASE_SIZE 96
#define TRAVELPI_MAP_PATH "assets/maps/world_map.qoi"
#define TRAVELPI_MAP_FALLBACK_PATH "assets/maps/world_map.png"
#define TRAVELPI_MAP_TILE_METADATA_PATH "assets/maps/tiles/tiles.txt"
#define TRAVELPI_MAP_TILE_PATH_FORMAT "assets/maps/tiles/z1/tile_%03d_%03d.qoi"
#define TRAVELPI_MAP_TILE_FALLBACK_PATH_FORMAT "assets/maps/tiles/z1/tile_%03d_%03d.png"
#define TRAVELPI_PLACEHOLDER_MAP_WIDTH 4096
#define TRAVELPI_PLACEHOLDER_MAP_HEIGHT 2048
#define TRAVELPI_MAP_TILE_CACHE_CAPACITY 24
#define TRAVELPI_MAP_TILE_LOADS_PER_FRAME 4
#define TRAVELPI_MAP_TILE_PREFETCH_MARGIN 0
#define TRAVELPI_MAP_TILE_MIN_ZOOM 7.00f

#define TRAVELPI_MAX_PHOTOS_PER_LOCATION 2
#define TRAVELPI_PREPARED_WIDTH 1920
#define TRAVELPI_PREPARED_HEIGHT 1080
#define TRAVELPI_PHOTO_LONG_EDGE_MAX 1600

#define TRAVELPI_CAMERA_RESPONSE 3.4f
#define TRAVELPI_ZOOM_RESPONSE 5.6f
#define TRAVELPI_MACRO_MAP_MARGIN 1.0f

#endif
