#ifndef TRAVELPI_APP_CONFIG_H
#define TRAVELPI_APP_CONFIG_H

#define TRAVELPI_TARGET_FPS 60
#define TRAVELPI_DEFAULT_SCREEN_WIDTH 1920
#define TRAVELPI_DEFAULT_SCREEN_HEIGHT 1080

#define TRAVELPI_MAP_PATH "assets/maps/world_map.qoi"
#define TRAVELPI_MAP_FALLBACK_PATH "assets/maps/world_map.png"
#define TRAVELPI_PLACEHOLDER_MAP_WIDTH 4096
#define TRAVELPI_PLACEHOLDER_MAP_HEIGHT 2048

#define TRAVELPI_MAX_PHOTOS_PER_LOCATION 4
#define TRAVELPI_PREPARED_WIDTH 1920
#define TRAVELPI_PREPARED_HEIGHT 1080
#define TRAVELPI_PHOTO_LONG_EDGE_MAX 1280

#define TRAVELPI_CAMERA_RESPONSE 6.8f
#define TRAVELPI_ZOOM_RESPONSE 5.6f
#define TRAVELPI_MACRO_MAP_MARGIN 0.94f

#endif
